Started logging messages
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: Off
Info:        Surfaces: Off
Info:        BReps: On
Info:        Create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW IGES v1.5.3-dev
Info:    Reading D:\Users\Edgar\ZEMAX\OBJECTS\WEIRD_THING.IGS
Info:    Reading D:\Users\Edgar\ZEMAX\OBJECTS\WEIRD_THING.IGS
Info:    File completely read
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 24 surfaces in file
Info:    Found 15 trimmed surfaces in file
Info:    Found 0 B-reps in file
Info:    Found 0 B-rep faces in file
Info:    
Info:    Processing D:\Users\Edgar\ZEMAX\OBJECTS\WEIRD_THING.IGS
Info:    IGES/Nlib processing done
Info:    Transferring D:\Users\Edgar\ZEMAX\OBJECTS\WEIRD_THING.IGS
Info:    Using 3D tolerance 0.0142634
Info:    Working on trimmed surface 133
Info:          UV Curve (~length 0.000459384) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:          Snipping loop from segment 0, parameter -1.70967 to segment 1, parameter -1.70967
Info:          Snipping loop from segment 2, parameter -5.87233 to segment 3, parameter -5.87233
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:          UV Curve (~length 0.000113666) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:          UV Curve (~length 0.00583284) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 153
Info:          UV Curve was degenerate -- deleting
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 167
Info:        Created trimmed surface 
Info:    Working on trimmed surface 207
Info:        Singularity found at u = 0, v = [0, 9.83635], width = 1.28556e-014
Info:          UV Curve (~length 0.0011501) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00108775) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 235
Info:        Singularity found at u = 0, v = [4.91818, 9.83635], width = 1.22641e-014
Info:        Singularity found at u = 4.91818, v = [4.91818, 9.83635], width = 1.22641e-014
Info:          UV Curve (~length 0.00969036) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.0111009) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.0127576) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00694291) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.000973385) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 263
Info:        Singularity found at u = 4.91818, v = [0, 9.83635], width = 1.28748e-014
Info:          UV Curve (~length 0.0246723) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 293
Info:        Singularity found at u = 0, v = [0, 5.53295], width = 2.31448e-014
Info:        Singularity found at u = 4.91818, v = [0, 5.53295], width = 2.33218e-014
Info:          UV Curve (~length 0.00722224) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00738648) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00646284) was degenerate in model space -- deleting
Info:          Editted end point to close gap
Info:          Editted end point to close gap
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 311
Info:          Snipping loop from segment 0, parameter 1.8105 to segment 1, parameter 1.8105
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on surface 313
Info:        Created surface 
Info:    Working on surface 315
Info:        Created surface 
Info:    Working on surface 317
Info:        Created surface 
Info:    Working on surface 319
Info:        Created surface 
Info:    Working on surface 321
Info:        Created surface 
Info:    Working on surface 323
Info:        Created surface 
Info:    Working on surface 325
Info:        Created surface 
Info:    Working on surface 327
Info:        Created surface 
Info:    Working on surface 329
Info:        Created surface 
Info:    Working on surface 331
Info:        Created surface 
Info:    Working on surface 333
Info:        Created surface 
Info:    Working on surface 335
Info:        Created surface 
Info:    Working on surface 337
Info:        Created surface 
Info:    Working on surface 339
Info:        Created surface 
Info:    Working on surface 341
Info:        Created surface 
Info:    Working on surface 343
Info:        Created surface 
Info:    Working on surface 345
Info:        Created surface 
Info:    Working on surface 347
Info:        Created surface 
Info:    Working on trimmed surface 451
Info:          UV Curve (~length 0.0127531) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00265248) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00753483) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:          UV Curve (~length 0.00265248) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 469
Info:        Created trimmed surface 
Info:    Working on trimmed surface 489
Info:        Singularity found at u = 0, v = [3.35402, 8.9242], width = 2.46067e-014
Info:        Singularity found at u = 4.91818, v = [3.35402, 8.9242], width = 2.46067e-014
Info:        Created trimmed surface 
Info:    Working on trimmed surface 521
Info:        Singularity found at u = 0, v = [0, 9.83635], width = 1.70944e-014
Info:          UV Curve (~length 0.0101873) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00553276) was degenerate in model space -- deleting
Info:          UV Curve (~length 0.00846697) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 541
Info:        Singularity found at u = 0, v = [0.947158, 6.44733], width = 2.69549e-014
Info:        Singularity found at u = 4.91818, v = [0.947158, 6.44733], width = 2.69515e-014
Info:          UV Curve (~length 0.00384495) was degenerate in model space -- deleting
Info:          Snipping loop from segment 1, parameter 5.29614 to segment 2, parameter 5.29614
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 565
Info:        Singularity found at u = 4.91818, v = [0, 9.83635], width = 1.70944e-014
Info:          UV Curve (~length 0.00553276) was degenerate in model space -- deleting
Info:              Tweaking curve ends
Info:              Tweaking curve ends
Info:        Created trimmed surface 
Info:    Working on trimmed surface 583
Info:        Created trimmed surface 
Info:    Working on surface 585
Info:        Created surface 
Info:    Working on surface 587
Info:        Created surface 
Info:    Working on surface 589
Info:        Created surface 
Info:    Working on surface 591
Info:        Created surface 
Info:    Working on surface 593
Info:        Created surface 
Info:    Working on surface 595
Info:        Created surface 
Info:    Finished with D:\Users\Edgar\ZEMAX\OBJECTS\WEIRD_THING.IGS
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:              24 found      24 created       0 failed
Info:    Trimmed Surfaces:      15 found      15 created       0 failed
Info:    Breps:                  0 found       0 created       0 failed
Info:    Didn't attempt to create IwPoints
Info:    Didn't attempt to create IwCurves
Info:    Didn't attempt to create IwSurfaces
Info:    Created 39 IwBreps with 39 IwFaces
