Started logging messages
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: Off
Info:        Surfaces: Off
Info:        BReps: On
Info:        Create IwAssembly/IwAssemblyInstance objects
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW STEP v1.2.3-dev
Info:    Reading D:\Users\Edgar\ZEMAX\OBJECTS\PRELIMINARY_LR_W5AM_270308_GEOMETRY.STEP
Info:    Processing D:\Users\Edgar\ZEMAX\OBJECTS\PRELIMINARY_LR_W5AM_270308_GEOMETRY.STEP
Info:    Transferring D:\Users\Edgar\ZEMAX\OBJECTS\PRELIMINARY_LR_W5AM_270308_GEOMETRY.STEP
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 93 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-005
Info:    Working on 333
Info:        Working on 1314
Info:            Working on 1120
Info:                Working on 2964
Info:                    Created 
Info:                Working on 1400
Info:                    Created 
Info:                Working on 1320
Info:                    Created 
Info:                Working on 1316
Info:                    Created 
Info:                Working on 3018
Info:                    Created 
Info:                Working on 1366
Info:                    Created 
Info:                Working on 1287
Info:                    Created 
Info:                Working on 1347
Info:                    Created 
Info:                Working on 1350
Info:                    Created 
Info:                Working on 2993
Info:                    Created 
Info:                Working on 1331
Info:                    Created 
Info:                Working on 1292
Info:                    Created 
Info:                Working on 1295
Info:                    Created 
Info:                Working on 1298
Info:                    Created 
Info:                Working on 2989
Info:                    Created 
Info:                Working on 1302
Info:                    Created 
Info:                Working on 1333
Info:                    Created 
Info:                Working on 1336
Info:                    Created 
Info:                Working on 1339
Info:                    Created 
Info:                Working on 54
Info:                    Created 
Info:                Working on 1343
Info:                    Created 
Info:                Working on 1307
Info:                    Created 
Info:                Working on 1310
Info:                    Created 
Info:                Working on 1402
Info:                    Created 
Info:                Working on 190
Info:                    Created 
Info:                Working on 1406
Info:                    Created 
Info:                Working on 1352
Info:                    Created 
Info:                Working on 1355
Info:                    Created 
Info:                Working on 1358
Info:                    Created 
Info:                Working on 79
Info:                    Created 
Info:                Working on 1362
Info:                    Created 
Info:                Working on 1115
Info:                    Created 
Info:                Working on 1111
Info:                    Created 
Info:                Working on 1106
Info:                    Created 
Info:                Working on 2593
Info:                    Created 
Info:                Working on 1102
Info:                    Created 
Info:                Working on 1096
Info:                    Created 
Info:                Working on 1109
Info:                    Created 
Info:                Working on 1088
Info:                    Created 
Info:                Working on 2551
Info:                    Created 
Info:                Working on 1089
Info:                    Created 
Info:                Working on 1082
Info:                    Created 
Info:                Working on 1084
Info:                    Created 
Info:                Working on 1164
Info:                    Created 
Info:                Working on 2689
Info:                    Created 
Info:                Working on 1205
Info:                    Created 
Info:                Working on 1160
Info:                    Created 
Info:                Working on 1141
Info:                    Created 
Info:                Working on 1162
Info:                    Created 
Info:                Working on 2788
Info:                    Created 
Info:                Working on 1202
Info:                    Created 
Info:                Working on 1156
Info:                    Created 
Info:                Working on 1181
Info:                    Created 
Info:                Working on 1183
Info:                    Created 
Info:                Working on 2709
Info:                    Created 
Info:                Working on 1145
Info:                    Created 
Info:                Working on 1148
Info:                    Created 
Info:                Working on 1151
Info:                    Created 
Info:                Working on 2651
Info:                    Created 
Info:                Working on 1196
Info:                    Created 
Info:                Working on 1199
Info:                    Created 
Info:                Working on 1126
Info:                    Created 
Info:                Working on 2622
Info:                    Created 
Info:                Working on 1133
Info:                    Created 
Info:                Working on 1137
Info:                    Created 
Info:                Working on 1188
Info:                    Created 
Info:                Working on 2756
Info:                    Created 
Info:                Working on 1192
Info:                    Created 
Info:                Working on 1180
Info:                    Created 
Info:                Working on 1174
Info:                    Created 
Info:                Working on 2679
Info:                    Created 
Info:                Working on 1171
Info:                    Created 
Info:                Working on 1176
Info:                    Created 
Info:                Working on 1178
Info:                    Created 
Info:                Working on 2850
Info:                    Created 
Info:                Working on 1246
Info:                    Created 
Info:                Working on 1243
Info:                    Created 
Info:                Working on 1240
Info:                    Created 
Info:                Working on 2822
Info:                    Created 
Info:                Working on 1212
Info:                    Created 
Info:                Working on 1214
Info:                    Created 
Info:                Working on 1216
Info:                    Created 
Info:                Working on 2829
Info:                    Created 
Info:                Working on 1222
Info:                    Created 
Info:                Working on 1225
Info:                    Created 
Info:                Working on 1228
Info:                    Created 
Info:                Working on 2801
Info:                    Created 
Info:                Working on 1232
Info:                    Created 
Info:                Working on 1282
Info:                    Created 
Info:                Working on 2957
Info:                    Created 
Info:                Working on 1248
Info:                    Created 
Info:                Working on 1284
Info:                    Created 
Info:                Working on 1277
Info:                    Created 
Info:                Working on 2891
Info:                    Created 
Info:                Working on 1265
Info:                    Created 
Info:                Working on 1269
Info:                    Created 
Info:                Working on 1251
Info:                    Created 
Info:                Working on 2921
Info:                    Created 
Info:                Working on 1253
Info:                    Created 
Info:                Working on 1259
Info:                    Created 
Info:                Working on 1263
Info:                    Created 
Info:                Working on 2877
Info:                    Created 
Info:                Working on 1323
Info:                    Created 
Info:                Working on 1325
Info:                    Created 
Info:                Working on 1327
Info:                    Created 
Info:                Working on 154
Info:                    Created 
Info:                Working on 1397
Info:                    Created 
Info:                Working on 1383
Info:                    Created 
Info:                Working on 1388
Info:                    Created 
Info:                Working on 150
Info:                    Created 
Info:                Working on 1386
Info:                    Created 
Info:                Working on 259
Info:                    Created 
Info:                Working on 1448
Info:                    Created 
Info:                Working on 1434
Info:                    Created 
Info:                Working on 1380
Info:                    Created 
Info:                Working on 113
Info:                    Created 
Info:                Working on 1440
Info:                    Created 
Info:                Working on 1442
Info:                    Created 
Info:                Working on 1445
Info:                    Created 
Info:                Working on 260
Info:                    Created 
Info:                Working on 1433
Info:                    Created 
Info:                Working on 1377
Info:                    Created 
Info:                Working on 1424
Info:                    Created 
Info:                Working on 1420
Info:                    Created 
Info:                Working on 1426
Info:                    Created 
Info:                Working on 218
Info:                    Created 
Info:                Working on 1423
Info:                    Created 
Info:                Working on 1480
Info:                    Created 
Info:                Working on 1468
Info:                    Created 
Info:                Working on 1470
Info:                    Created 
Info:                Working on 1415
Info:                    Created 
Info:                Working on 228
Info:                    Created 
Info:                Working on 1418
Info:                    Created 
Info:                Working on 1476
Info:                    Created 
Info:                Working on 1484
Info:                    Created 
Info:                Working on 239
Info:                    Created 
Info:                Working on 677
Info:                    Created 
Info:                Working on 2030
Info:                    Created 
Info:                Working on 637
Info:                    Created 
Info:                Working on 675
Info:                    Created 
Info:                Working on 709
Info:                    Created 
Info:                Working on 2088
Info:                    Created 
Info:                Working on 750
Info:                    Created 
Info:                Working on 634
Info:                    Created 
Info:                Working on 713
Info:                    Created 
Info:                Working on 2018
Info:                    Created 
Info:                Working on 756
Info:                    Created 
Info:                Working on 673
Info:                    Created 
Info:                Working on 683
Info:                    Created 
Info:                Working on 686
Info:                    Created 
Info:                Working on 707
Info:                    Created 
Info:                Working on 679
Info:                    Created 
Info:                Working on 691
Info:                    Created 
Info:                Working on 694
Info:                    Created 
Info:                Working on 688
Info:                    Created 
Info:                Working on 698
Info:                    Created 
Info:                Working on 701
Info:                    Created 
Info:                Working on 46
Info:                    Created 
Info:                Working on 47
Info:                    Created 
Info:                Working on 37
Info:                    Created 
Info:                Working on 1497
Info:                    Created 
Info:                Working on 48
Info:                    Created 
Info:                Working on 41
Info:                    Created 
Info:                Working on 24
Info:                    Created 
Info:                Working on 1463
Info:                    Created 
Info:                Working on 12
Info:                    Created 
Info:                Working on 19
Info:                    Created 
Info:                Working on 1510
Info:                    Created 
Info:                Working on 417
Info:                    Created 
Info:                Working on 421
Info:                    Created 
Info:                Working on 1527
Info:                    Created 
Info:                Working on 468
Info:                    Created 
Info:                Working on 420
Info:                    Created 
Info:                Working on 433
Info:                    Created 
Info:                Working on 1559
Info:                    Created 
Info:                Working on 409
Info:                    Created 
Info:                Working on 415
Info:                    Created 
Info:                Working on 430
Info:                    Created 
Info:                Working on 1612
Info:                    Created 
Info:                Working on 18
Info:                    Created 
Info:                Working on 492
Info:                    Created 
Info:                Working on 487
Info:                    Created 
Info:                Working on 1641
Info:                    Created 
Info:                Working on 443
Info:                    Created 
Info:                Working on 493
Info:                    Created 
Info:                Working on 1621
Info:                    Created 
Info:                Working on 450
Info:                    Created 
Info:                Working on 444
Info:                    Created 
Info:                Working on 1595
Info:                    Created 
Info:                Working on 438
Info:                    Created 
Info:                Working on 451
Info:                    Created 
Info:                Working on 503
Info:                    Created 
Info:                Working on 1734
Info:                    Created 
Info:                Working on 529
Info:                    Created 
Info:                Working on 511
Info:                    Created 
Info:                Working on 440
Info:                    Created 
Info:                Working on 1725
Info:                    Created 
Info:                Working on 499
Info:                    Created 
Info:                Working on 494
Info:                    Created 
Info:                Working on 517
Info:                    Created 
Info:                Working on 1606
Info:                    Created 
Info:                Working on 478
Info:                    Created 
Info:                Working on 536
Info:                    Created 
Info:                Working on 518
Info:                    Created 
Info:                Working on 1675
Info:                    Created 
Info:                Working on 543
Info:                    Created 
Info:                Working on 515
Info:                    Created 
Info:                Working on 504
Info:                    Created 
Info:                Working on 1769
Info:                    Created 
Info:                Working on 1166
Info:                    Created 
Info:                Working on 1703
Info:                    Created 
Info:                Working on 510
Info:                    Created 
Info:                Working on 1782
Info:                    Created 
Info:                Working on 583
Info:                    Created 
Info:                Working on 591
Info:                    Created 
Info:                Working on 1792
Info:                    Created 
Info:                Working on 620
Info:                    Created 
Info:                Working on 608
Info:                    Created 
Info:                Working on 1857
Info:                    Created 
Info:                Working on 606
Info:                    Created 
Info:                Working on 604
Info:                    Created 
Info:                Working on 621
Info:                    Created 
Info:                Working on 615
Info:                    Created 
Info:                Working on 610
Info:                    Created 
Info:                Working on 579
Info:                    Created 
Info:                Working on 1807
Info:                    Created 
Info:                Working on 568
Info:                    Created 
Info:                Working on 571
Info:                    Created 
Info:                Working on 1832
Info:                    Created 
Info:                Working on 562
Info:                    Created 
Info:                Working on 553
Info:                    Created 
Info:                Working on 1758
Info:                    Created 
Info:                Working on 630
Info:                    Created 
Info:                Working on 624
Info:                    Created 
Info:                Working on 1838
Info:                    Created 
Info:                Working on 658
Info:                    Created 
Info:                Working on 647
Info:                    Created 
Info:                Working on 667
Info:                    Created 
Info:                Working on 1776
Info:                    Created 
Info:                Working on 597
Info:                    Created 
Info:                Working on 1916
Info:                    Created 
Info:                Working on 643
Info:                    Created 
Info:                Working on 1933
Info:                    Created 
Info:                Working on 654
Info:                    Created 
Info:                Working on 649
Info:                    Created 
Info:                Working on 1906
Info:                    Created 
Info:                Working on 730
Info:                    Created 
Info:                Working on 747
Info:                    Created 
Info:                Working on 2044
Info:                    Created 
Info:                Working on 740
Info:                    Created 
Info:                Working on 742
Info:                    Created 
Info:                Working on 728
Info:                    Created 
Info:                Working on 800
Info:                    Created 
Info:                Working on 718
Info:                    Created 
Info:                Working on 2007
Info:                    Created 
Info:                Working on 733
Info:                    Created 
Info:                Working on 736
Info:                    Created 
Info:                Working on 785
Info:                    Created 
Info:                Working on 787
Info:                    Created 
Info:                Working on 793
Info:                    Created 
Info:                Working on 783
Info:                    Created 
Info:                Working on 2067
Info:                    Created 
Info:                Working on 773
Info:                    Created 
Info:                Working on 776
Info:                    Created 
Info:                Working on 774
Info:                    Created 
Info:                Working on 760
Info:                    Created 
Info:                Working on 768
Info:                    Created 
Info:                Working on 771
Info:                    Created 
Info:                Working on 2101
Info:                    Created 
Info:                Working on 831
Info:                    Created 
Info:                Working on 834
Info:                    Created 
Info:                Working on 2207
Info:                    Created 
Info:                Working on 820
Info:                    Created 
Info:                Working on 823
Info:                    Created 
Info:                Working on 2222
Info:                    Created 
Info:                Working on 806
Info:                    Created 
Info:                Working on 2182
Info:                    Created 
Info:                Working on 812
Info:                    Created 
Info:                Working on 815
Info:                    Created 
Info:                Working on 2284
Info:                    Created 
Info:                Working on 877
Info:                    Created 
Info:                Working on 2273
Info:                    Created 
Info:                Working on 804
Info:                    Created 
Info:                Working on 860
Info:                    Created 
Info:                Working on 2237
Info:                    Created 
Info:                Working on 868
Info:                    Created 
Info:                Working on 2227
Info:                    Created 
Info:                Working on 847
Info:                    Created 
Info:                Working on 850
Info:                    Created 
Info:                Working on 2248
Info:                    Created 
Info:                Working on 914
Info:                    Created 
Info:                Working on 2339
Info:                    Created 
Info:                Working on 918
Info:                    Created 
Info:                Working on 842
Info:                    Created 
Info:                Working on 2197
Info:                    Created 
Info:                Working on 904
Info:                    Created 
Info:                Working on 2297
Info:                    Created 
Info:                Working on 908
Info:                    Created 
Info:                Working on 912
Info:                    Created 
Info:                Working on 891
Info:                    Created 
Info:                Working on 2308
Info:                    Created 
Info:                Working on 961
Info:                    Created 
Info:                Working on 881
Info:                    Created 
Info:                Working on 2262
Info:                    Created 
Info:                Working on 885
Info:                    Created 
Info:                Working on 947
Info:                    Created 
Info:                Working on 2358
Info:                    Created 
Info:                Working on 954
Info:                    Created 
Info:                Working on 957
Info:                    Created 
Info:                Working on 2376
Info:                    Created 
Info:                Working on 940
Info:                    Created 
Info:                Working on 945
Info:                    Created 
Info:                Working on 2322
Info:                    Created 
Info:                Working on 932
Info:                    Created 
Info:                Working on 992
Info:                    Created 
Info:                Working on 2422
Info:                    Created 
Info:                Working on 996
Info:                    Created 
Info:                Working on 1001
Info:                    Created 
Info:                Working on 2328
Info:                    Created 
Info:                Working on 985
Info:                    Created 
Info:                Working on 2432
Info:                    Created 
Info:                Working on 970
Info:                    Created 
Info:                Working on 973
Info:                    Created 
Info:                Working on 2443
Info:                    Created 
Info:                Working on 1035
Info:                    Created 
Info:                Working on 2540
Info:                    Created 
Info:                Working on 962
Info:                    Created 
Info:                Working on 965
Info:                    Created 
Info:                Working on 2498
Info:                    Created 
Info:                Working on 1027
Info:                    Created 
Info:                Working on 2487
Info:                    Created 
Info:                Working on 1011
Info:                    Created 
Info:                Working on 1013
Info:                    Created 
Info:                Working on 2507
Info:                    Created 
Info:                Working on 1020
Info:                    Created 
Info:                Working on 2577
Info:                    Created 
Info:                Working on 1002
Info:                    Created 
Info:                Working on 1005
Info:                    Created 
Info:                Working on 2461
Info:                    Created 
Info:                Working on 1066
Info:                    Created 
Info:                Working on 2520
Info:                    Created 
Info:                Working on 1071
Info:                    Created 
Info:                Working on 2535
Info:                    Created 
Info:                Created 
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Created 
Info:    Working on BRep 1314
Info:        Created BRep 
Info:    Finished with D:\Users\Edgar\ZEMAX\OBJECTS\PRELIMINARY_LR_W5AM_270308_GEOMETRY.STEP
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
