Started logging messages
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: Off
Info:        Surfaces: Off
Info:        BReps: On
Info:        Create IwAssembly/IwAssemblyInstance objects
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW STEP v1.2.3-dev
Info:    Reading D:\Users\Edgar\ZEMAX\OBJECTS\LSM04_OCT_SCAN_LENS.STEP
Info:    Processing D:\Users\Edgar\ZEMAX\OBJECTS\LSM04_OCT_SCAN_LENS.STEP
Info:    Transferring D:\Users\Edgar\ZEMAX\OBJECTS\LSM04_OCT_SCAN_LENS.STEP
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 93 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-005
Info:    Working on 2368
Info:        Working on 2367
Info:            Working on 2616
Info:                Working on 5332
Info:                    Created 
Info:                Working on 2611
Info:                    Created 
Info:                Working on 2615
Info:                    Created 
Info:                Created 
Info:            Working on 2548
Info:                Working on 5394
Info:                    Created 
Info:                Working on 2543
Info:                    Created 
Info:                Working on 2547
Info:                    Created 
Info:                Created 
Info:            Working on 2463
Info:                Working on 5195
Info:                    Created 
Info:                Working on 2552
Info:                    Created 
Info:                Working on 2556
Info:                    Created 
Info:                Working on 2559
Info:                    Created 
Info:                Working on 2562
Info:                    Created 
Info:                Working on 5205
Info:                    Created 
Info:                Working on 2597
Info:                    Created 
Info:                Working on 2599
Info:                    Created 
Info:                Working on 2602
Info:                    Created 
Info:                Working on 2605
Info:                    Created 
Info:                Working on 2608
Info:                    Created 
Info:                Working on 2580
Info:                    Created 
Info:                Working on 2583
Info:                    Created 
Info:                Working on 2586
Info:                    Created 
Info:                Working on 5304
Info:                    Created 
Info:                Working on 2590
Info:                    Created 
Info:                Working on 2646
Info:                    Created 
Info:                Working on 2649
Info:                    Created 
Info:                Working on 2652
Info:                    Created 
Info:                Working on 2655
Info:                    Created 
Info:                Working on 2658
Info:                    Created 
Info:                Working on 2633
Info:                    Created 
Info:                Working on 2636
Info:                    Created 
Info:                Working on 5493
Info:                    Created 
Info:                Working on 2641
Info:                    Created 
Info:                Working on 2644
Info:                    Created 
Info:                Working on 2620
Info:                    Created 
Info:                Working on 2623
Info:                    Created 
Info:                Working on 2626
Info:                    Created 
Info:                Working on 2629
Info:                    Created 
Info:                Working on 5471
Info:                    Created 
Info:                Working on 2418
Info:                    Created 
Info:                Working on 2415
Info:                    Working on 4558
Info:                        Created 
Info:                    Created 
Info:                Working on 2456
Info:                    Created 
Info:                Working on 2379
Info:                    Created 
Info:                Working on 4513
Info:                    Created 
Info:                Working on 2384
Info:                    Created 
Info:                Working on 2443
Info:                    Created 
Info:                Working on 4680
Info:                    Created 
Info:                Working on 2449
Info:                    Working on 4674
Info:                        Created 
Info:                    Created 
Info:                Working on 2452
Info:                    Created 
Info:                Working on 4705
Info:                    Created 
Info:                Working on 2403
Info:                    Working on 4520
Info:                        Created 
Info:                    Created 
Info:                Working on 2406
Info:                    Created 
Info:                Working on 4605
Info:                    Created 
Info:                Working on 2434
Info:                    Created 
Info:                Working on 4643
Info:                    Created 
Info:                Working on 2389
Info:                    Created 
Info:                Working on 4533
Info:                    Created 
Info:                Working on 2394
Info:                    Created 
Info:                Working on 2493
Info:                    Created 
Info:                Working on 4586
Info:                    Created 
Info:                Working on 2424
Info:                    Working on 4580
Info:                        Created 
Info:                    Created 
Info:                Working on 2427
Info:                    Created 
Info:                Working on 2478
Info:                    Created 
Info:                Working on 4836
Info:                    Created 
Info:                Working on 2485
Info:                    Created 
Info:                Working on 4858
Info:                    Created 
Info:                Working on 2491
Info:                    Created 
Info:                Working on 4807
Info:                    Created 
Info:                Working on 5165
Info:                    Created 
Info:                Working on 2462
Info:                    Created 
Info:                Created 
Info:            Working on 4221
Info:                Working on 4712
Info:                    Created 
Info:                Working on 2467
Info:                    Working on 4782
Info:                        Created 
Info:                    Created 
Info:                Working on 2527
Info:                    Working on 5004
Info:                        Created 
Info:                    Created 
Info:                Working on 2530
Info:                    Working on 5046
Info:                        Created 
Info:                    Created 
Info:                Working on 2533
Info:                    Working on 5084
Info:                        Created 
Info:                    Created 
Info:                Working on 2536
Info:                    Working on 5077
Info:                        Created 
Info:                    Created 
Info:                Working on 2509
Info:                    Working on 4942
Info:                        Created 
Info:                    Created 
Info:                Working on 2512
Info:                    Working on 4995
Info:                        Created 
Info:                    Created 
Info:                Working on 2515
Info:                    Working on 5022
Info:                        Created 
Info:                    Created 
Info:                Working on 2518
Info:                    Working on 5016
Info:                        Created 
Info:                    Created 
Info:                Working on 2521
Info:                    Working on 5009
Info:                        Created 
Info:                    Created 
Info:                Working on 2494
Info:                    Working on 4844
Info:                        Created 
Info:                    Created 
Info:                Working on 2497
Info:                    Working on 4896
Info:                        Created 
Info:                    Created 
Info:                Working on 2500
Info:                    Working on 4912
Info:                        Created 
Info:                    Created 
Info:                Working on 2503
Info:                    Working on 4905
Info:                        Created 
Info:                    Created 
Info:                Working on 2506
Info:                    Working on 4900
Info:                        Created 
Info:                    Created 
Info:                Working on 2565
Info:                    Working on 5201
Info:                        Created 
Info:                    Created 
Info:                Working on 2568
Info:                    Working on 5259
Info:                        Created 
Info:                    Created 
Info:                Working on 2571
Info:                    Created 
Info:                Working on 2575
Info:                    Created 
Info:                Working on 2578
Info:                    Created 
Info:                Working on 2694
Info:                    Created 
Info:                Working on 2697
Info:                    Created 
Info:                Working on 2701
Info:                    Created 
Info:                Working on 2704
Info:                    Created 
Info:                Working on 2707
Info:                    Created 
Info:                Working on 2678
Info:                    Working on 5566
Info:                        Created 
Info:                    Created 
Info:                Working on 2682
Info:                    Working on 5570
Info:                        Created 
Info:                    Created 
Info:                Working on 2685
Info:                    Working on 5607
Info:                        Created 
Info:                    Created 
Info:                Working on 2688
Info:                    Working on 5652
Info:                        Created 
Info:                    Created 
Info:                Working on 2691
Info:                    Working on 5700
Info:                        Created 
Info:                    Created 
Info:                Working on 2663
Info:                    Working on 5499
Info:                        Created 
Info:                    Created 
Info:                Working on 2666
Info:                    Working on 5501
Info:                        Created 
Info:                    Created 
Info:                Working on 2669
Info:                    Working on 5543
Info:                        Created 
Info:                    Created 
Info:                Working on 2672
Info:                    Working on 5581
Info:                        Created 
Info:                    Created 
Info:                Working on 2675
Info:                    Created 
Info:                Working on 5
Info:                    Created 
Info:                Working on 6
Info:                    Created 
Info:                Working on 3
Info:                    Working on 4324
Info:                        Created 
Info:                    Created 
Info:                Working on 2377
Info:                    Working on 4486
Info:                        Created 
Info:                    Created 
Info:                Working on 24
Info:                    Working on 4410
Info:                        Created 
Info:                    Created 
Info:                Working on 22
Info:                    Working on 4413
Info:                        Created 
Info:                    Created 
Info:                Working on 17
Info:                    Created 
Info:                Working on 15
Info:                    Created 
Info:                Working on 12
Info:                    Created 
Info:                Working on 2747
Info:                    Created 
Info:                Working on 2749
Info:                    Created 
Info:                Working on 2753
Info:                    Created 
Info:                Working on 33
Info:                    Created 
Info:                Working on 26
Info:                    Created 
Info:                Working on 2733
Info:                    Created 
Info:                Working on 2736
Info:                    Created 
Info:                Working on 2739
Info:                    Created 
Info:                Working on 2743
Info:                    Created 
Info:                Working on 2717
Info:                    Created 
Info:                Working on 2720
Info:                    Created 
Info:                Working on 2723
Info:                    Created 
Info:                Working on 2726
Info:                    Created 
Info:                Working on 2729
Info:                    Created 
Info:                Working on 2794
Info:                    Created 
Info:                Working on 2797
Info:                    Created 
Info:                Working on 2800
Info:                    Created 
Info:                Working on 2710
Info:                    Created 
Info:                Working on 2714
Info:                    Created 
Info:                Working on 2779
Info:                    Created 
Info:                Working on 2782
Info:                    Created 
Info:                Working on 2785
Info:                    Created 
Info:                Working on 2788
Info:                    Created 
Info:                Working on 2791
Info:                    Created 
Info:                Working on 2765
Info:                    Created 
Info:                Working on 2768
Info:                    Created 
Info:                Working on 2771
Info:                    Created 
Info:                Working on 2774
Info:                    Created 
Info:                Working on 2777
Info:                    Created 
Info:                Working on 2845
Info:                    Created 
Info:                Working on 2755
Info:                    Created 
Info:                Working on 2758
Info:                    Created 
Info:                Working on 2761
Info:                    Created 
Info:                Working on 2764
Info:                    Working on 5805
Info:                        Created 
Info:                    Created 
Info:                Working on 2831
Info:                    Created 
Info:                Working on 2834
Info:                    Created 
Info:                Working on 2837
Info:                    Created 
Info:                Working on 2840
Info:                    Created 
Info:                Working on 2813
Info:                    Created 
Info:                Working on 2815
Info:                    Created 
Info:                Working on 2818
Info:                    Working on 6027
Info:                        Created 
Info:                    Created 
Info:                Working on 2822
Info:                    Working on 6025
Info:                        Created 
Info:                    Created 
Info:                Working on 2825
Info:                    Created 
Info:                Working on 2828
Info:                    Working on 6035
Info:                        Created 
Info:                    Created 
Info:                Working on 2802
Info:                    Working on 5918
Info:                        Created 
Info:                    Created 
Info:                Working on 2805
Info:                    Working on 5646
Info:                        Created 
Info:                    Created 
Info:                Working on 2808
Info:                    Working on 5938
Info:                        Created 
Info:                    Created 
Info:                Working on 2811
Info:                    Working on 5933
Info:                        Created 
Info:                    Created 
Info:                Working on 2879
Info:                    Working on 6209
Info:                        Created 
Info:                    Created 
Info:                Working on 2882
Info:                    Working on 6248
Info:                        Created 
Info:                    Created 
Info:                Working on 2885
Info:                    Created 
Info:                Working on 2888
Info:                    Working on 6287
Info:                        Created 
Info:                    Created 
Info:                Working on 2891
Info:                    Working on 6354
Info:                        Created 
Info:                    Created 
Info:                Working on 2862
Info:                    Working on 6157
Info:                        Created 
Info:                    Created 
Info:                Working on 2865
Info:                    Working on 6139
Info:                        Created 
Info:                    Created 
Info:                Working on 2868
Info:                    Working on 5911
Info:                        Created 
Info:                    Created 
Info:                Working on 2871
Info:                    Created 
Info:                Working on 2875
Info:                    Created 
Info:                Working on 2849
Info:                    Created 
Info:                Working on 2851
Info:                    Created 
Info:                Working on 2854
Info:                    Created 
Info:                Working on 2857
Info:                    Created 
Info:                Working on 2860
Info:                    Created 
Info:                Working on 2928
Info:                    Created 
Info:                Working on 2931
Info:                    Created 
Info:                Working on 2934
Info:                    Working on 6571
Info:                        Created 
Info:                    Created 
Info:                Working on 2937
Info:                    Working on 6604
Info:                        Created 
Info:                    Created 
Info:                Working on 2911
Info:                    Working on 6400
Info:                        Created 
Info:                    Created 
Info:                Working on 2913
Info:                    Working on 6462
Info:                        Created 
Info:                    Created 
Info:                Working on 2916
Info:                    Working on 6442
Info:                        Created 
Info:                    Created 
Info:                Working on 2919
Info:                    Working on 6170
Info:                        Created 
Info:                    Created 
Info:                Working on 2922
Info:                    Working on 6526
Info:                        Created 
Info:                    Created 
Info:                Working on 2897
Info:                    Created 
Info:                Working on 2900
Info:                    Created 
Info:                Working on 2903
Info:                    Created 
Info:                Working on 2906
Info:                    Created 
Info:                Working on 2909
Info:                    Created 
Info:                Working on 2976
Info:                    Created 
Info:                Working on 2979
Info:                    Created 
Info:                Working on 2983
Info:                    Created 
Info:                Working on 2986
Info:                    Created 
Info:                Working on 2895
Info:                    Working on 6392
Info:                        Created 
Info:                    Created 
Info:                Working on 2961
Info:                    Working on 6654
Info:                        Created 
Info:                    Created 
Info:                Working on 2964
Info:                    Working on 6649
Info:                        Created 
Info:                    Created 
Info:                Working on 2967
Info:                    Working on 6680
Info:                        Created 
Info:                    Created 
Info:                Working on 2970
Info:                    Working on 6732
Info:                        Created 
Info:                    Created 
Info:                Working on 2973
Info:                    Working on 6730
Info:                        Created 
Info:                    Created 
Info:                Working on 2946
Info:                    Created 
Info:                Working on 2949
Info:                    Working on 6574
Info:                        Created 
Info:                    Created 
Info:                Working on 2952
Info:                    Working on 6629
Info:                        Created 
Info:                    Created 
Info:                Working on 2955
Info:                    Working on 6614
Info:                        Created 
Info:                    Created 
Info:                Working on 2958
Info:                    Created 
Info:                Working on 3023
Info:                    Created 
Info:                Working on 3026
Info:                    Created 
Info:                Working on 3030
Info:                    Created 
Info:                Working on 3033
Info:                    Created 
Info:                Working on 2943
Info:                    Created 
Info:                Working on 3008
Info:                    Created 
Info:                Working on 3011
Info:                    Created 
Info:                Working on 3014
Info:                    Created 
Info:                Working on 3017
Info:                    Created 
Info:                Working on 3020
Info:                    Created 
Info:                Working on 2994
Info:                    Created 
Info:                Working on 2997
Info:                    Created 
Info:                Working on 3000
Info:                    Created 
Info:                Working on 3003
Info:                    Created 
Info:                Working on 3070
Info:                    Created 
Info:                Working on 3072
Info:                    Created 
Info:                Working on 3075
Info:                    Created 
Info:                Working on 3078
Info:                    Created 
Info:                Working on 2990
Info:                    Created 
Info:                Working on 3055
Info:                    Created 
Info:                Working on 3057
Info:                    Created 
Info:                Working on 3060
Info:                    Working on 6926
Info:                        Created 
Info:                    Created 
Info:                Working on 3064
Info:                    Working on 6952
Info:                        Created 
Info:                    Created 
Info:                Working on 3067
Info:                    Working on 6987
Info:                        Created 
Info:                    Created 
Info:                Working on 3041
Info:                    Working on 6859
Info:                        Created 
Info:                    Created 
Info:                Working on 3044
Info:                    Created 
Info:                Working on 3048
Info:                    Working on 6876
Info:                        Created 
Info:                    Created 
Info:                Working on 3051
Info:                    Created 
Info:                Working on 3117
Info:                    Working on 7354
Info:                        Created 
Info:                    Created 
Info:                Working on 3120
Info:                    Created 
Info:                Working on 3123
Info:                    Working on 7342
Info:                        Created 
Info:                    Created 
Info:                Working on 3126
Info:                    Created 
Info:                Working on 3036
Info:                    Working on 6864
Info:                        Created 
Info:                    Created 
Info:                Working on 3103
Info:                    Working on 7208
Info:                        Created 
Info:                    Created 
Info:                Working on 3106
Info:                    Working on 7229
Info:                        Created 
Info:                    Created 
Info:                Working on 3109
Info:                    Working on 7269
Info:                        Created 
Info:                    Created 
Info:                Working on 3112
Info:                    Working on 7337
Info:                        Created 
Info:                    Created 
Info:                Working on 3115
Info:                    Working on 7307
Info:                        Created 
Info:                    Created 
Info:                Working on 3089
Info:                    Working on 7102
Info:                        Created 
Info:                    Created 
Info:                Working on 3092
Info:                    Working on 7152
Info:                        Created 
Info:                    Created 
Info:                Working on 3095
Info:                    Working on 7135
Info:                        Created 
Info:                    Created 
Info:                Working on 3098
Info:                    Working on 7184
Info:                        Created 
Info:                    Created 
Info:                Working on 3101
Info:                    Working on 7167
Info:                        Created 
Info:                    Created 
Info:                Working on 3169
Info:                    Working on 7493
Info:                        Created 
Info:                    Created 
Info:                Working on 3172
Info:                    Working on 7528
Info:                        Created 
Info:                    Created 
Info:                Working on 3080
Info:                    Working on 7074
Info:                        Created 
Info:                    Created 
Info:                Working on 3083
Info:                    Working on 7068
Info:                        Created 
Info:                    Created 
Info:                Working on 3086
Info:                    Working on 7062
Info:                        Created 
Info:                    Created 
Info:                Working on 3153
Info:                    Working on 7438
Info:                        Created 
Info:                    Created 
Info:                Working on 3156
Info:                    Working on 7491
Info:                        Created 
Info:                    Created 
Info:                Working on 3159
Info:                    Working on 7488
Info:                        Created 
Info:                    Created 
Info:                Working on 3162
Info:                    Created 
Info:                Working on 3166
Info:                    Created 
Info:                Working on 3138
Info:                    Created 
Info:                Working on 3141
Info:                    Working on 7423
Info:                        Created 
Info:                    Created 
Info:                Working on 3144
Info:                    Working on 7417
Info:                        Created 
Info:                    Created 
Info:                Working on 3147
Info:                    Working on 7402
Info:                        Created 
Info:                    Created 
Info:                Working on 3150
Info:                    Working on 7445
Info:                        Created 
Info:                    Created 
Info:                Working on 3217
Info:                    Created 
Info:                Working on 3128
Info:                    Created 
Info:                Working on 3131
Info:                    Created 
Info:                Working on 3134
Info:                    Created 
Info:                Working on 3201
Info:                    Working on 7787
Info:                        Created 
Info:                    Created 
Info:                Working on 3203
Info:                    Created 
Info:                Working on 3206
Info:                    Working on 7776
Info:                        Created 
Info:                    Created 
Info:                Working on 3209
Info:                    Created 
Info:                Working on 3212
Info:                    Working on 7825
Info:                        Created 
Info:                    Created 
Info:                Working on 3186
Info:                    Working on 7638
Info:                        Created 
Info:                    Created 
Info:                Working on 3188
Info:                    Working on 7631
Info:                        Created 
Info:                    Created 
Info:                Working on 3191
Info:                    Working on 7639
Info:                        Created 
Info:                    Created 
Info:                Working on 3194
Info:                    Working on 7681
Info:                        Created 
Info:                    Created 
Info:                Working on 3197
Info:                    Created 
Info:                Working on 3263
Info:                    Created 
Info:                Working on 3175
Info:                    Created 
Info:                Working on 3178
Info:                    Created 
Info:                Working on 3181
Info:                    Created 
Info:                Working on 2413
Info:                    Created 
Info:                Working on 3248
Info:                    Created 
Info:                Working on 3251
Info:                    Created 
Info:                Working on 3254
Info:                    Working on 7858
Info:                        Created 
Info:                    Created 
Info:                Working on 3257
Info:                    Created 
Info:                Working on 3260
Info:                    Created 
Info:                Working on 3234
Info:                    Created 
Info:                Working on 3237
Info:                    Created 
Info:                Working on 3240
Info:                    Created 
Info:                Working on 3243
Info:                    Created 
Info:                Working on 3246
Info:                    Created 
Info:                Working on 3220
Info:                    Created 
Info:                Working on 3223
Info:                    Created 
Info:                Working on 3226
Info:                    Created 
Info:                Working on 3229
Info:                    Created 
Info:                Working on 3232
Info:                    Created 
Info:                Working on 3298
Info:                    Created 
Info:                Working on 3302
Info:                    Working on 7965
Info:                        Created 
Info:                    Created 
Info:                Working on 3305
Info:                    Created 
Info:                Working on 3308
Info:                    Working on 8004
Info:                        Created 
Info:                    Created 
Info:                Working on 3282
Info:                    Working on 7955
Info:                        Created 
Info:                    Created 
Info:                Working on 3285
Info:                    Working on 7949
Info:                        Created 
Info:                    Created 
Info:                Working on 3288
Info:                    Working on 7942
Info:                        Created 
Info:                    Created 
Info:                Working on 3291
Info:                    Created 
Info:                Working on 3294
Info:                    Working on 7977
Info:                        Created 
Info:                    Created 
Info:                Working on 3267
Info:                    Working on 7890
Info:                        Created 
Info:                    Created 
Info:                Working on 3270
Info:                    Working on 7931
Info:                        Created 
Info:                    Created 
Info:                Working on 3273
Info:                    Working on 7924
Info:                        Created 
Info:                    Created 
Info:                Working on 3276
Info:                    Created 
Info:                Working on 3279
Info:                    Working on 7913
Info:                        Created 
Info:                    Created 
Info:                Working on 3346
Info:                    Created 
Info:                Working on 3349
Info:                    Working on 8132
Info:                        Created 
Info:                    Created 
Info:                Working on 3352
Info:                    Working on 8126
Info:                        Created 
Info:                    Created 
Info:                Working on 3355
Info:                    Working on 8169
Info:                        Created 
Info:                    Created 
Info:                Working on 3358
Info:                    Working on 8162
Info:                        Created 
Info:                    Created 
Info:                Working on 3332
Info:                    Created 
Info:                Working on 3336
Info:                    Created 
Info:                Working on 3339
Info:                    Created 
Info:                Working on 3342
Info:                    Working on 8149
Info:                        Created 
Info:                    Created 
Info:                Working on 3315
Info:                    Working on 7986
Info:                        Created 
Info:                    Created 
Info:                Working on 3318
Info:                    Working on 8045
Info:                        Created 
Info:                    Created 
Info:                Working on 3321
Info:                    Working on 8030
Info:                        Created 
Info:                    Created 
Info:                Working on 3324
Info:                    Created 
Info:                Working on 3328
Info:                    Created 
Info:                Working on 3393
Info:                    Created 
Info:                Working on 3396
Info:                    Created 
Info:                Working on 3399
Info:                    Created 
Info:                Working on 3403
Info:                    Created 
Info:                Working on 3314
Info:                    Created 
Info:                Working on 3380
Info:                    Created 
Info:                Working on 3383
Info:                    Working on 8274
Info:                        Created 
Info:                    Created 
Info:                Working on 3386
Info:                    Created 
Info:                Working on 3389
Info:                    Created 
Info:                Working on 3392
Info:                    Created 
Info:                Working on 3364
Info:                    Created 
Info:                Working on 3367
Info:                    Created 
Info:                Working on 3370
Info:                    Created 
Info:                Working on 3373
Info:                    Working on 8246
Info:                        Created 
Info:                    Created 
Info:                Working on 3377
Info:                    Created 
Info:                Working on 3441
Info:                    Created 
Info:                Working on 3444
Info:                    Created 
Info:                Working on 3447
Info:                    Working on 8442
Info:                        Created 
Info:                    Created 
Info:                Working on 3450
Info:                    Working on 8504
Info:                        Created 
Info:                    Created 
Info:                Working on 3361
Info:                    Working on 8157
Info:                        Created 
Info:                    Created 
Info:                Working on 3428
Info:                    Working on 8406
Info:                        Created 
Info:                    Created 
Info:                Working on 3431
Info:                    Working on 8402
Info:                        Created 
Info:                    Created 
Info:                Working on 3434
Info:                    Working on 8439
Info:                        Created 
Info:                    Created 
Info:                Working on 3437
Info:                    Working on 8411
Info:                        Created 
Info:                    Created 
Info:                Working on 3411
Info:                    Working on 8341
Info:                        Created 
Info:                    Created 
Info:                Working on 3414
Info:                    Working on 8303
Info:                        Created 
Info:                    Created 
Info:                Working on 3417
Info:                    Created 
Info:                Working on 3421
Info:                    Created 
Info:                Working on 3424
Info:                    Created 
Info:                Working on 3483
Info:                    Created 
Info:                Working on 8659
Info:                    Created 
Info:                Working on 3487
Info:                    Created 
Info:                Working on 3404
Info:                    Created 
Info:                Working on 3407
Info:                    Created 
Info:                Working on 3466
Info:                    Created 
Info:                Working on 8604
Info:                    Created 
Info:                Working on 3470
Info:                    Created 
Info:                Working on 3474
Info:                    Created 
Info:                Working on 3477
Info:                    Created 
Info:                Working on 8629
Info:                    Created 
Info:                Working on 3453
Info:                    Created 
Info:                Working on 3456
Info:                    Created 
Info:                Working on 3459
Info:                    Created 
Info:                Working on 8573
Info:                    Created 
Info:                Working on 3464
Info:                    Created 
Info:                Working on 3520
Info:                    Created 
Info:                Working on 3523
Info:                    Created 
Info:                Working on 8805
Info:                    Created 
Info:                Working on 3527
Info:                    Created 
Info:                Working on 3451
Info:                    Created 
Info:                Working on 3507
Info:                    Created 
Info:                Working on 8740
Info:                    Created 
Info:                Working on 3512
Info:                    Created 
Info:                Working on 3515
Info:                    Created 
Info:                Working on 3518
Info:                    Created 
Info:                Working on 8692
Info:                    Created 
Info:                Working on 3494
Info:                    Created 
Info:                Working on 3498
Info:                    Created 
Info:                Working on 3501
Info:                    Created 
Info:                Working on 8719
Info:                    Created 
Info:                Working on 3505
Info:                    Created 
Info:                Working on 3561
Info:                    Created 
Info:                Working on 3564
Info:                    Created 
Info:                Working on 69
Info:                    Created 
Info:                Working on 3568
Info:                    Created 
Info:                Working on 3542
Info:                    Created 
Info:                Working on 3544
Info:                    Created 
Info:                Working on 3547
Info:                    Created 
Info:                Working on 59
Info:                    Created 
Info:                Working on 3551
Info:                    Created 
Info:                Working on 3553
Info:                    Created 
Info:                Working on 3556
Info:                    Created 
Info:                Working on 3531
Info:                    Created 
Info:                Working on 8830
Info:                    Created 
Info:                Working on 3535
Info:                    Created 
Info:                Working on 3537
Info:                    Created 
Info:                Working on 3540
Info:                    Created 
Info:                Working on 3605
Info:                    Created 
Info:                Working on 168
Info:                    Created 
Info:                Working on 140
Info:                    Created 
Info:                Working on 99
Info:                    Created 
Info:                Working on 245
Info:                    Created 
Info:                Working on 207
Info:                    Created 
Info:                Working on 195
Info:                    Created 
Info:                Working on 228
Info:                    Created 
Info:                Working on 357
Info:                    Created 
Info:                Working on 339
Info:                    Created 
Info:                Working on 3688
Info:                    Working on 334
Info:                        Created 
Info:                    Created 
Info:                Working on 3692
Info:                    Created 
Info:                Working on 3671
Info:                    Created 
Info:                Working on 304
Info:                    Created 
Info:                Working on 280
Info:                    Created 
Info:                Working on 436
Info:                    Created 
Info:                Working on 371
Info:                    Created 
Info:                Working on 3712
Info:                    Created 
Info:                Working on 3716
Info:                    Created 
Info:                Working on 3719
Info:                    Created 
Info:                Working on 3722
Info:                    Working on 414
Info:                        Created 
Info:                    Created 
Info:                Working on 3783
Info:                    Working on 591
Info:                        Created 
Info:                    Created 
Info:                Working on 613
Info:                    Created 
Info:                Working on 3700
Info:                    Created 
Info:                Working on 3704
Info:                    Created 
Info:                Working on 3707
Info:                    Created 
Info:                Working on 3770
Info:                    Working on 524
Info:                        Created 
Info:                    Created 
Info:                Working on 3773
Info:                    Working on 490
Info:                        Created 
Info:                    Created 
Info:                Working on 526
Info:                    Created 
Info:                Working on 469
Info:                    Created 
Info:                Working on 738
Info:                    Created 
Info:                Working on 3823
Info:                    Created 
Info:                Working on 3827
Info:                    Created 
Info:                Working on 3746
Info:                    Created 
Info:                Working on 3806
Info:                    Working on 638
Info:                        Created 
Info:                    Created 
Info:                Working on 3809
Info:                    Working on 623
Info:                        Created 
Info:                    Created 
Info:                Working on 3812
Info:                    Working on 688
Info:                        Created 
Info:                    Created 
Info:                Working on 705
Info:                    Created 
Info:                Working on 643
Info:                    Created 
Info:                Working on 819
Info:                    Created 
Info:                Working on 3853
Info:                    Created 
Info:                Working on 845
Info:                    Created 
Info:                Working on 763
Info:                    Created 
Info:                Working on 3842
Info:                    Created 
Info:                Working on 789
Info:                    Created 
Info:                Working on 3899
Info:                    Created 
Info:                Working on 965
Info:                    Created 
Info:                Working on 3832
Info:                    Created 
Info:                Working on 922
Info:                    Created 
Info:                Working on 3892
Info:                    Created 
Info:                Working on 950
Info:                    Created 
Info:                Working on 3897
Info:                    Created 
Info:                Working on 850
Info:                    Created 
Info:                Working on 3882
Info:                    Created 
Info:                Working on 880
Info:                    Created 
Info:                Working on 3937
Info:                    Created 
Info:                Working on 1122
Info:                    Created 
Info:                Working on 3871
Info:                    Created 
Info:                Working on 870
Info:                    Created 
Info:                Working on 3929
Info:                    Created 
Info:                Working on 1097
Info:                    Created 
Info:                Working on 3934
Info:                    Created 
Info:                Working on 3913
Info:                    Created 
Info:                Working on 1038
Info:                    Created 
Info:                Working on 3921
Info:                    Created 
Info:                Working on 1070
Info:                    Created 
Info:                Working on 1279
Info:                    Created 
Info:                Working on 3908
Info:                    Working on 960
Info:                        Created 
Info:                    Created 
Info:                Working on 3967
Info:                    Working on 1142
Info:                        Created 
Info:                    Created 
Info:                Working on 3970
Info:                    Working on 1237
Info:                        Created 
Info:                    Created 
Info:                Working on 3973
Info:                    Working on 1234
Info:                        Created 
Info:                    Created 
Info:                Working on 1300
Info:                    Created 
Info:                Working on 1153
Info:                    Created 
Info:                Working on 3962
Info:                    Working on 1148
Info:                        Created 
Info:                    Created 
Info:                Working on 4025
Info:                    Created 
Info:                Working on 4028
Info:                    Working on 1339
Info:                        Created 
Info:                    Created 
Info:                Working on 1370
Info:                    Created 
Info:                Working on 1350
Info:                    Created 
Info:                Working on 1317
Info:                    Created 
Info:                Working on 1498
Info:                    Created 
Info:                Working on 4056
Info:                    Working on 1493
Info:                        Created 
Info:                    Created 
Info:                Working on 4060
Info:                    Working on 1491
Info:                        Created 
Info:                    Created 
Info:                Working on 4063
Info:                    Working on 1537
Info:                        Created 
Info:                    Created 
Info:                Working on 4066
Info:                    Working on 1544
Info:                        Created 
Info:                    Created 
Info:                Working on 4043
Info:                    Working on 1442
Info:                        Created 
Info:                    Created 
Info:                Working on 1466
Info:                    Created 
Info:                Working on 1402
Info:                    Created 
Info:                Working on 4035
Info:                    Working on 1397
Info:                        Created 
Info:                    Created 
Info:                Working on 4039
Info:                    Created 
Info:                Working on 4103
Info:                    Created 
Info:                Working on 1657
Info:                    Created 
Info:                Working on 1626
Info:                    Created 
Info:                Working on 1583
Info:                    Created 
Info:                Working on 1810
Info:                    Created 
Info:                Working on 4147
Info:                    Created 
Info:                Working on 4151
Info:                    Created 
Info:                Working on 4154
Info:                    Created 
Info:                Working on 4129
Info:                    Working on 1676
Info:                        Created 
Info:                    Created 
Info:                Working on 4132
Info:                    Working on 1701
Info:                        Created 
Info:                    Created 
Info:                Working on 4135
Info:                    Working on 1695
Info:                        Created 
Info:                    Created 
Info:                Working on 4138
Info:                    Working on 1803
Info:                        Created 
Info:                    Created 
Info:                Working on 1828
Info:                    Created 
Info:                Working on 1935
Info:                    Created 
Info:                Working on 1687
Info:                    Created 
Info:                Working on 4177
Info:                    Working on 1880
Info:                        Created 
Info:                    Created 
Info:                Working on 4181
Info:                    Created 
Info:                Working on 4184
Info:                    Created 
Info:                Working on 1899
Info:                    Created 
Info:                Working on 1885
Info:                    Created 
Info:                Working on 2019
Info:                    Created 
Info:                Working on 1953
Info:                    Created 
Info:                Created 
Info:            Working on 4327
Info:                Working on 1993
Info:                    Created 
Info:                Working on 4225
Info:                    Created 
Info:                Working on 4202
Info:                    Created 
Info:                Working on 4205
Info:                    Created 
Info:                Working on 4208
Info:                    Created 
Info:                Working on 4211
Info:                    Created 
Info:                Working on 3911
Info:                    Created 
Info:                Working on 4269
Info:                    Created 
Info:                Working on 4272
Info:                    Created 
Info:                Working on 2137
Info:                    Created 
Info:                Working on 4277
Info:                    Created 
Info:                Working on 4280
Info:                    Working on 2126
Info:                        Created 
Info:                    Created 
Info:                Working on 4254
Info:                    Created 
Info:                Working on 4257
Info:                    Created 
Info:                Working on 2122
Info:                    Created 
Info:                Working on 4261
Info:                    Created 
Info:                Working on 4266
Info:                    Created 
Info:                Working on 2257
Info:                    Created 
Info:                Working on 4241
Info:                    Created 
Info:                Working on 4245
Info:                    Created 
Info:                Working on 4248
Info:                    Created 
Info:                Working on 4251
Info:                    Created 
Info:                Working on 2030
Info:                    Created 
Info:                Working on 4309
Info:                    Created 
Info:                Working on 4313
Info:                    Working on 2203
Info:                        Created 
Info:                    Created 
Info:                Working on 4316
Info:                    Created 
Info:                Working on 4319
Info:                    Created 
Info:                Working on 2223
Info:                    Created 
Info:                Working on 4295
Info:                    Working on 2193
Info:                        Created 
Info:                    Created 
Info:                Working on 4298
Info:                    Created 
Info:                Working on 2219
Info:                    Created 
Info:                Working on 4304
Info:                    Created 
Info:                Working on 4353
Info:                    Created 
Info:                Working on 4284
Info:                    Created 
Info:                Working on 2146
Info:                    Created 
Info:                Working on 4291
Info:                    Created 
Info:                Working on 4342
Info:                    Created 
Info:                Working on 4347
Info:                    Created 
Info:                Working on 2354
Info:                    Created 
Info:                Working on 4352
Info:                    Created 
Info:                Working on 4330
Info:                    Created 
Info:                Working on 4333
Info:                    Working on 2297
Info:                        Created 
Info:                    Created 
Info:                Working on 2278
Info:                    Created 
Info:                Working on 4339
Info:                    Created 
Info:                Created 
Info:            Created 
Info:        Working on 2366
Info:            Created 
Info:        Created 
Info:    Working on BRep 2367
Info:        Created BRep 
Info:    Finished with D:\Users\Edgar\ZEMAX\OBJECTS\LSM04_OCT_SCAN_LENS.STEP
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
